### ISSUE TITLE
NPEs in com.onfido.android.sdk.capture.ui.camera.face.CameraSource

### ISSUE THREAD

**Issue by bogonilo** [onfido/onfido-android-sdk#163]
- `onfido-capture-sdk` version: 10.0.0
- Android API version(s): 8-9-10-11

Since we updated to the version 10.0.0 of your SDK we've been experiencing quite some NPEs, they all seem related to the record video screen, plus some other NPE in the take picture screen, which if I understand correctly they are both related to the CameraSource class. Unfortunately I don't have the exact steps to reproduce but this is influencing quite a lot of our users.

Stacktrace for the video one:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.MediaRecorder.setOutputFile(java.lang.String)' on a null object reference
    at com.onfido.android.sdk.capture.ui.camera.face.CameraSource.startVideo
    at com.onfido.android.sdk.capture.ui.camera.face.CameraSourcePreview.startVideo
    at com.onfido.android.sdk.capture.ui.camera.face.CameraSourcePreview.startVideo
    at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.startVideoCapture
    at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.access$startVideoCapture
    at com.onfido.android.sdk.capture.ui.camera.CaptureActivity$inflateCaptureButton$1.onClick
    at android.view.View.performClick(View.java:7498)
    at android.view.View.performClickInternal(View.java:7475)
    at android.view.View.access$3600(View.java:833)
    at android.view.View$PerformClick.run(View.java:28663)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:236)
    at android.app.ActivityThread.main(ActivityThread.java:7879)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

```
take picture:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.onfido.android.sdk.capture.ui.camera.face.CameraSource.takePicture(com.onfido.android.sdk.capture.ui.camera.face.CameraSource$ShutterCallback, com.onfido.android.sdk.capture.ui.camera.face.CameraSource$PictureCallback, boolean)' on a null object reference
    at com.onfido.android.sdk.capture.ui.camera.face.CameraSourcePreview.takePicture
    at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.capture
    at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.access$capture
    at com.onfido.android.sdk.capture.ui.camera.CaptureActivity$setupCaptureButton$1.onClick
    at android.view.View.performClick(View.java:7335)
    at android.view.View.performClickInternal(View.java:7304)
    at android.view.View.access$3600(View.java:815)
    at android.view.View$PerformClick.run(View.java:28155)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7711)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by gokhanaliccii** [comment]
@bogonilo I'm sorry for the crashes. We have fixed the first crash which will be available in the next version but the second one is in our backlog. We'll keep you posted if there's any update on the ticket

**Comment by renaudboulard** [comment]
We experience the same bug in production already 42 of our users affected in 4 days, we are looking forward for the fix, @gokhanaliccii when will the next version be released?

**Comment by marcoRS** [comment]
Any update on when this will be released? This is now our highest crash in our app :-/.

**Comment by bogonilo** [comment]
Any news about the release? New ETA? 🙂

**Comment by marcoRS** [comment]
Would love to know about this as well.. This is still our biggest crash in our app :-/

**Comment by musagil** [comment]
hi @marcoRS, @bogonilo, and  @renaudboulard 

We've published a new version that contains a fix for the NPE. 

Please bump to the latest version, thanks

**Comment by marcoRS** [comment]
@musagil These NPEs appear to still be happening in our app:

`
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void com.onfido.android.sdk.capture.ui.camera.face.CameraSource.takePicture(com.onfido.android.sdk.capture.ui.camera.face.CameraSource$ShutterCallback, com.onfido.android.sdk.capture.ui.camera.face.CameraSource$PictureCallback, boolean)' on a null object reference
`

**Comment by marcoRS** [comment]
@gokhanaliccii  @seewah Any thoughts on this? This crash is still happening in our app for the latest version.

**Comment by bogonilo** [comment]
@gokhanaliccii also for us the crash doesn't seem to be solved completely, the one I referred in the description as "takePicture". The other one instead it seems to have been fixed. Can you reopen?

**Comment by marcoRS** [comment]
On our app we have no dev configs in particular. This crash happens in the latest version and the previous one. We are unable to reproduce this crash on our devices

We have the following device stats:

48% Android 11
27% Android 10
17% Android 9
8% Android 8

79% Samsung
7% Motorola
3% LGE
3% HUAWEI
8% Other (7)

**Comment by bogonilo** [comment]
Unfortunately it's still happening in version 10.3.0 of your SDK 

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.onfido.android.sdk.capture.ui.camera.view.CameraSource.takePicture(com.onfido.android.sdk.capture.ui.camera.view.CameraSource$ShutterCallback, com.onfido.android.sdk.capture.ui.camera.view.CameraSource$PictureCallback, boolean)' on a null object reference
    at com.onfido.android.sdk.capture.ui.camera.view.CameraSourcePreview.takePicture
    at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.capture
    at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.setupCaptureButton$lambda-13
    at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.$r8$lambda$2ZKQN5Ws-kxsfpzA-QdCkgf4bOo
    at com.onfido.android.sdk.capture.ui.camera.CaptureActivity$$InternalSyntheticLambda$0$b6b4fb1cca4e0252d3e7f188439f987f9d6ceae2efac86419009757a79db6f21$0.onClick
    at android.view.View.performClick(View.java:7281)
    at android.view.View.performClickInternal(View.java:7255)
    at android.view.View.access$3600(View.java:828)
    at android.view.View$PerformClick.run(View.java:27925)
    at android.os.Handler.handleCallback(Handler.java:900)
    at android.os.Handler.dispatchMessage(Handler.java:103)
    at android.os.Looper.loop(Looper.java:219)
    at android.app.ActivityThread.main(ActivityThread.java:8393)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
```

**Comment by sadeqzadeh** [comment]
That's unfortunate, thanks for reporting. We're looking into this issue again.

**Comment by musagil** [comment]
@marcoRS Can you please test it with the latest release (10.3.1)? With the latest release, we have changed the lifecycle of the camera source. I hope it has solved the issue.

**Comment by MoemenMostafa** [comment]
We are using version 10.2.0 and we are facing the same issue. Any one released an app with SDK version 10.3.1 yet?

**Comment by fuller** [comment]
We've released our app including version 10.3.1, but unfortunately we are still seeing the same issue.

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.onfido.android.sdk.capture.ui.camera.view.CameraSource.takePicture(com.onfido.android.sdk.capture.ui.camera.view.CameraSource$ShutterCallback, com.onfido.android.sdk.capture.ui.camera.view.CameraSource$PictureCallback, boolean)' on a null object reference
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSourcePreview.takePicture(CameraSourcePreview.java:8)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.capture(CaptureActivity.java:50)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.setupCaptureButton$lambda-13(CaptureActivity.java:5)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.lambda$2ZKQN5Ws-kxsfpzA-QdCkgf4bOo(CaptureActivity.java)
       at com.onfido.android.sdk.capture.ui.camera.-$$Lambda$CaptureActivity$2ZKQN5Ws-kxsfpzA-QdCkgf4bOo.onClick(lambda:2)
       at android.view.View.performClick(View.java:8160)
       at android.view.View.performClickInternal(View.java:8137)
       at android.view.View.access$3700(View.java:888)
       at android.view.View$PerformClick.run(View.java:30236)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8512)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by musagil** [comment]
Hey,
The issues are fixed in our new release 10.3.2, please update your dependency and let us know if you could reproduce this again.

I'm closing the issue feel free to open it if you think the issue hasn't been resolved

**Comment by kimrtaylor** [comment]
Hi @musagil , we've updated to 10.3.2 and released our app but we're still seeing the issue


`Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void com.onfido.android.sdk.capture.ui.camera.view.CameraSource.takePicture(com.onfido.android.sdk.capture.ui.camera.view.CameraSource$ShutterCallback, com.onfido.android.sdk.capture.ui.camera.view.CameraSource$PictureCallback, boolean)' on a null object reference
com.onfido.android.sdk.capture.ui.camera.view.CameraSourcePreview.takePicture (CameraSourcePreview.java:8)
com.onfido.android.sdk.capture.ui.camera.CaptureActivity.capture (CaptureActivity.java:50)
com.onfido.android.sdk.capture.ui.camera.CaptureActivity.setupCaptureButton$lambda-13 (CaptureActivity.java:8)
com.onfido.android.sdk.capture.ui.camera.CaptureActivity.$r8$lambda$2ZKQN5Ws-kxsfpzA-QdCkgf4bOo (CaptureActivity.java)
com.onfido.android.sdk.capture.ui.camera.CaptureActivity$$InternalSyntheticLambda$0$b6b4fb1cca4e0252d3e7f188439f987f9d6ceae2efac86419009757a79db6f21$0.onClick (CaptureActivity.java:2)
`

**Comment by kimrtaylor** [comment]
Hi @musagil  @jdeebee  @gokhanaliccii @seewah , I'm afraid this ticket may need reopening (see previous message)

**Comment by kimrtaylor** [comment]
@musagil  @jdeebee  @gokhanaliccii  @seewah Could we re-open this issue please?

**Comment by musagil** [comment]
Thanks, @kimrtaylor for your report, we have reopened this issue again and will take care of it as soon as possible.
