### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'Camera.getParameters()' on a null object reference

### ISSUE THREAD

**Issue by xrigau** [onfido/onfido-android-sdk#214]
#### What was the expected behaviour?

The app shouldn't crash, the Onfido document capture should take the photo and proceed to the next step.

#### What happened instead?

The app crashes in the Document Capture step of the Onfido flow.

#### Version info:

- `onfido-capture-sdk` version: `com.onfido.sdk.capture:onfido-capture-sdk-core:12.3.0` - Notice we're using `onfido-capture-sdk-core`
- Android API version(s): According to Firebase, this crash has occurred in Android 8, 9, 10, 11 and 12.

- `compileSdkVersion`: 33
- `targetSdkVersion`: 31
- `minSdkVersion`: 27
- Support library version (if applicable): N/A

#### Steps to reproduce:

We don't know, we haven't been able to reproduce this issue.

#### Onfido Flow initialization code:

```kotlin
val tokenExpirationHandler = // ...
    val config = OnfidoConfig.builder(context)
        .withSDKToken("token", tokenExpirationHandler)
        .build()
    val intent = onfido.createIntent(config)
    startActivity(intent)
```

#### Issue severity information (number of users/crashes if applicable):

This issue has 19 crash events affecting 9 users for the past 2 weeks.

#### Additional LogCat output:

Stacktrace from Firebase:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.Camera$Parameters android.hardware.Camera.getParameters()' on a null object reference
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSource.getPictureSize(CameraSource.java:4)
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSource.getPictureDimension(CameraSource.java)
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSourcePreview.onLayout(CameraSourcePreview.java:14)
       at android.view.View.layout(View.java:24475)
       at android.view.ViewGroup.layout(ViewGroup.java:7383)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       [...]
```

Another variation of this also from Firebase:

```
Fatal Exception: java.lang.RuntimeException: getParameters failed (empty parameters)
       at android.hardware.Camera.native_getParameters(Camera.java)
       at android.hardware.Camera.getParameters(Camera.java:2210)
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSource.getPictureSize(CameraSource.java:4)
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSource.getPictureDimension(CameraSource.java)
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSourcePreview.onLayout(CameraSourcePreview.java:14)
       at android.view.View.layout(View.java:22087)
       at android.view.ViewGroup.layout(ViewGroup.java:6337)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       [...]
```

#### Other useful info:

Thanks to the analytics hook, we have the following details with this crash report:

```
mode: {"orientation":"PORTRAIT"}
country: [Many - we operate in KE, UG, GH and NG]
name: DOCUMENT_CAPTURE_FRONT
doc_type: [national_id, passport, and probably others]
is_autocapture: false
```

**Comment by kimrtaylor** [comment]
We have the same issue. We are using the Onfido Capture SDK v13.1.0

Our stacktrace:

```
Fatal Exception: java.lang.RuntimeException: getParameters failed (empty parameters)
       at android.hardware.Camera.native_getParameters(Camera.java)
       at android.hardware.Camera.getParameters(Camera.java:1896)
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSource.getPictureSize(SourceFile)
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSource.getPictureDimension(SourceFile)
       at com.onfido.android.sdk.capture.ui.camera.view.CameraSourcePreview.onLayout(SourceFile)
       at android.view.View.layout(View.java:17637)
       at android.view.ViewGroup.layout(ViewGroup.java:5575)
```

**Comment by xrigau** [comment]
Hey @Tobi0077 @gurpreet-onfido from the release notes of the latest release ([13.0.1](https://github.com/onfido/onfido-android-sdk/releases/tag/13.0.1)), it seems this should've been fixed, correct?

**Comment by gurpreet-onfido** [comment]
Hello @xrigau Yes, my team has confirmed that it is fixed in the release 13.0.1. Please let me know if there is anything else I can help you with.

Kind regards
Gurpreet Singh

**Comment by xrigau** [comment]
Awesome, thanks!

**Comment by cagdassozer** [comment]
We're still getting these crashes with the latest version (13.2.0)
