### ISSUE TITLE
java.lang.IllegalStateException: Disposable already set!

### ISSUE THREAD

**Issue by patrickdw1991** [onfido/onfido-android-sdk#52]
#### What was the expected behaviour?
User records video during onfido flow

#### What happened instead?
Crash during video during onfido flow

#### Version info:

- `onfido-capture-sdk` version: 4.5.1
- Android API version(s):

- `compileSdkVersion`: 28
- `targetSdkVersion`: 28
- `minSdkVersion`: 21
- Support library version (if applicable):
16.0.0

#### Steps to reproduce:
Unsure looks like this randomly happens to people when they are moving trough the video part of the onfido flow.

#### Onfido Flow initialization code:
```
        onfidoClient = OnfidoFactory.create(this).client
        val locale = Locale("", pickedCountryCode)
        val countryCodeIso3 = locale.isO3Country

        val onfidoCountryCode = findOnfidoCountryCode(countryCodeIso3)

        val captureStep = createCaptureStep(onfidoDocumentType ?: return, onfidoCountryCode)
        val flowSteps = arrayOf(captureStep, FaceCaptureStep(FaceCaptureVariant.VIDEO))

        val onfidoConfig = OnfidoConfig.builder()
                .withApplicant(userIdentificationVerification.applicantId)
                .withToken(userIdentificationVerification.token)
                .withCustomFlow(flowSteps)
                .build()
        onfidoClient.startActivityForResult(this, REQUEST_CODE_ONFIDO, onfidoConfig)
```

#### Issue severity information (number of users/crashes if applicable):
54 crashes 52 users

#### Additional LogCat output:
```
java.lang.IllegalStateException: Disposable already set!
    at io.reactivex.d.a.b.c(DisposableHelper.java:144)
    at io.reactivex.d.a.b.b(DisposableHelper.java:70)
    at io.reactivex.d.e.c.z$a.a(ObservableTimer.java:74)
    at io.reactivex.d.e.c.z.a(ObservableTimer.java:40)
    at io.reactivex.Observable.b(Observable.java:10179)
    at io.reactivex.d.e.c.g.a(ObservableDoOnEach.java:42)
    at io.reactivex.Observable.b(Observable.java:10179)
    at io.reactivex.d.e.c.w$1.run(ObservableSubscribeOn.java:39)
    at io.reactivex.Scheduler$1.run(Scheduler.java:134)
    at io.reactivex.d.g.f.run(ScheduledRunnable.java:59)
    at io.reactivex.d.g.f.call(ScheduledRunnable.java:51)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    at java.lang.Thread.run(Thread.java:764)
```

#### Other useful info:
Affected devices:
```

SM-A320FL
DRA-L21
S6
W-V600
JERRY2
DIG-L01
SM-J330FN
SM-G900F
Konnect_601
FREDDY
SM-J510FN
Redmi 6A
HTC One
SM-A510F
LM-X210(G)
SGH-I337M
AUM-L29
Neffos_C9A
P10
5047Y
SM-G530FZ
SM-A310F
FP2
SM-J330F
A1
DUA-L22
ATU-L21
ONEPLUS A5000
Sunny3 Mini
SM-J530F
Nexus 5X
Neffos C5a
PSP5513DUO
SM-J250F
F3113
SM-J415FN
SM-G390F
SM-G901F
SM-J400F
```

**Comment by sergiomarquesmoura** [comment]
Hi @patrickdw1991 . A fix for this issue is in review and should be live with the next release, which should be next week

**Comment by sergiomarquesmoura** [comment]
@patrickdw1991 We just released the fix for this crash as part of our `4.9.0` release. Changelog here: https://github.com/onfido/onfido-android-sdk/blob/master/CHANGELOG.MD#490

**Comment by araratthehero** [comment]
Hi @sergiomarquesmoura. I work on the same project with @patrickdw1991. We updated the library but we still get reports of the same issue.
